### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by GaoNeng-wWw** [TeamVastsea/ToYou-Frontend#83]
- [x] dashboard layout ( #77 )
- [x] picure list ( #77 )
- [x] picture upload ( #86 )
- [x] picture context menu
  - [x] context-menu-components ( #85 )
- [ ] picture select
- [ ] picture update
- [x] picture delete ( #87 )
- [x] picture shared ( #87 )
- [x] folder list
- [x] folder create ( #89 )
- [x] folder update (#89) aka. rename
- [x] folder delete (#89 )
- [x] folder rename ( #89 )
- [ ] #94

**Comment by M397749490** [comment]
:+1
